version: "3"

services:
  app:
    container_name: MyAnimeStream
    build: .
    image: myanimestream
    restart: always
    ports:
      - 80:80
    networks:
      - backend
    environment:
      - "MONGO_URI=mongodb://database:27017"
    depends_on:
      - database
  database:
    container_name: MongoDB
    image: mongo
    restart: always
    expose:
      - "27017"
    networks:
      - backend

networks:
  backend: {}