version: "3"

services:
  app:
    container_name: MyAnimeStream
    build: .
    image: myanimestream
    restart: always
    ports:
      - 80:80
    networks:
      - frontend
      - backend
    depends_on:
      - database
  database:
    container_name: MongoDB
    image: mongo
    restart: always
    expose:
      - "27017"
    networks:
      - backend

networks:
  frontend:
    external: true

  backend:
    external: false